### PR TITLE
danish translations for 2b99e4c

### PR DESCRIPTION
**Pull request by srn**

### CODE REVIEW

**Comment by srn** [comment]
updated for DeskSMS rename.

**Comment by koush** [comment]
Oh, I believe I already did this. Can you check and make sure I didn't mess anything up?

**Comment by koush** [comment]
I just did a string replace.

**Comment by srn** [comment]
I parsed the wrong commit id. It's the "missed call logging" a37cc3343e47e47a193aecbe461a5787687c2e41

**Comment by koush** [comment]
Mind reapplying this commit on top of my recent changes?

**Comment by srn** [comment]
9b25288c2d2fb0a361c7ca11839cd775371c26ba is already up-to-date. Even with DeskSMS renaming and missed_call_from etc..

**Pull request merged**
