### PR TITLE
Edited values-es/strings.xml via GitHub

### PR DESCRIPTION
**Pull request by realjumy**

### CODE REVIEW

**Comment by koush** [comment]
Ah, looks like someone else beat you to this, by editing the previous version as well. Mind looking over their changes and leaving some feedback/changes?

**Comment by realjumy** [comment]
It seems to been latin-american (south american) spanish instead of neutral spanish (from Spain and rest of the wolrd) because he uses "computadora" instead of "ordenador" and the order of some verbs are not in the correct order (for neutral spanish).

There are some gramatical fails like "extenciones", that should be written as "extensiones".

Another mistake: "Iniciar sesión un email de Google Apps puede que no funcione", it should be "Puede que no funcione si usas una cuenta de email de Google Apps".

But it seems to be good translation. I think that you should give the option to choose latin-american spanish or neutral spanish, some sentences can be strange depending of the dialect used.

Ah, and I do NOT do this for a redeem code. Your ROM manager was a very useful tool with a lot of free utilities and I think that this is a good way to thanks you (I bought the paid version aswell). You gave a lot of free things and is natural that you receive a lot of free things too.

**Comment by koush** [comment]
@realjumy Thanks. Should I move the existing one from values-es to values-es-somethingelse? Do you which region that belongs in?

**Comment by koush** [comment]
From what I can see, there is values-es, values-es-rES, and values-es-rUS

**Comment by koush** [comment]
Or should I just simply accept yours in favor?

**Comment by koush** [comment]
Here's a code anyways :) e8d2adf8

**Comment by realjumy** [comment]
Thanks for the code. I think I will give to someone because since I have Google Talk I never use SMS.

I think that my translation can be "spanish - traditional", and the other translation can be "spanish - american" or "spanish-US".

**Comment by realjumy** [comment]
"Spanish - traditional" is the same that "spanish - es".

**Pull request merged**
